"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SCENARIOS = exports.SCENARIO_REGISTRY = exports.PLATFORMS = exports.PLATFORM_REGISTRY = exports.GAME_REGISTRY = exports.ArcadeRenderer = exports.ARCADE_GAMES = exports.PlayerStyle = exports.PacmanRenderer = void 0;
var index_1 = require("./pacman/index");
Object.defineProperty(exports, "PacmanRenderer", { enumerable: true, get: function () { return index_1.PacmanRenderer; } });
Object.defineProperty(exports, "PlayerStyle", { enumerable: true, get: function () { return index_1.PlayerStyle; } });
var arcade_renderer_1 = require("./shared/arcade-renderer");
Object.defineProperty(exports, "ARCADE_GAMES", { enumerable: true, get: function () { return arcade_renderer_1.ARCADE_GAMES; } });
Object.defineProperty(exports, "ArcadeRenderer", { enumerable: true, get: function () { return arcade_renderer_1.ArcadeRenderer; } });
Object.defineProperty(exports, "GAME_REGISTRY", { enumerable: true, get: function () { return arcade_renderer_1.GAME_REGISTRY; } });
var types_1 = require("./shared/types");
Object.defineProperty(exports, "PLATFORM_REGISTRY", { enumerable: true, get: function () { return types_1.PLATFORM_REGISTRY; } });
Object.defineProperty(exports, "PLATFORMS", { enumerable: true, get: function () { return types_1.PLATFORMS; } });
Object.defineProperty(exports, "SCENARIO_REGISTRY", { enumerable: true, get: function () { return types_1.SCENARIO_REGISTRY; } });
Object.defineProperty(exports, "SCENARIOS", { enumerable: true, get: function () { return types_1.SCENARIOS; } });
